config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  get 'home', to: 'static#home'
  get 'contact', to: 'static#contact'
  get 'privacy', to: 'static#privacy'

  resources :people, param: :random_id
  get 'verify_email/:verification_token', to: 'people#verify_email'
  get 'change_password', to: 'people#change_password'
  get 'change_state/:random_id/:state', to: 'people#change_state'

  resources :groups
  get 'done/:id', to: 'groups#done'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'
end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password validations: false
	attr_accessor :password_confirmation

  has_secure_token :random_id
  has_secure_token :verification_token

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :group, required: false

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :about, presence: true
  validates :password, length: { in: 14..72 }, if: Proc.new { |p| p.isGodmother && p.password != nil }
  validates :password, confirmation: true, if: Proc.new { |p| p.isGodmother }
  validates :password_confirmation, presence: true, unless: Proc.new { |p| p.password.blank? }

  ROLES = {
    1 => :mentee,
    2 => :mentor,
    3 => :godmother # This role means, you are a godmother only, but not a mentor
  }

  STATES = {
    1 => :unverified,
    2 => :verified,
    3 => :okay,
    4 => :waiting,
    5 => :in_group,
    23 => :declined,
    42 => :done
  }

  def role_name
    ROLES[self.role]
  end

  def role_id
    self.role
  end

  def role_id=(r)
    if r
      self.role = r
      case self.role
      when 1
        self.isGodmother = false
      when 3
        self.isGodmother = true
      end
    end
  end

  def role_name=(r)
    r = ROLES.key(r.to_sym)

    if r      
      self.role = r
      case self.role
      when 1
        self.isGodmother = false
      when 3
        self.isGodmother = true
      end
    else
      self.role = 1
    end
  end

  def role_all
    ROLES.collect { |k, v| k }
  end

  def state_name
    STATES[self.state]
  end

  def state_name=(s)
    s = STATES.key(s.to_sym)

    if s
      self.state = s
    else
      self.state = 1
    end
  end

  def to_param
    random_id
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).people
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
    joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip.downcase).first_or_create!
    end
  end

  def is_godmother
    self.isGodmother
  end

  def is_godmother=(g)
    case self.role
    when 1
      self.isGodmother = false
    when 2
      self.isGodmother = g
    when 3
      self.isGodmother = true
    end
  end

  def align_group_state
    unless self.state_name == :done
      if self.state_name == :in_group && self.group_id.blank?
        self.state_name = :okay
      elsif self.state_name != :in_group && self.group_id
        self.state_name = :in_group
      end
    end
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  QUESTIONS = [
		["What is two plus two? (in digits)", "4"],
		["What is the number before twelve? (in digits)", "11"],
		["Five times two is what? (in digits)", "10"],
		["Insert the next number in this sequence: 10, 11, 12, 13, 14, … (in digits)", "15"],
		["What is five times five? (in digits)", "25"],
		["Ten divided by two is what? (in digits)", "5"],
		["What day comes after Monday?", "tuesday"],
		["What is the last month of the year?", "december"],
		["How many minutes are in an hour? (in digits)", "60"],
		["What is the opposite of down?", "up"],
		["What is the opposite of north?", "south"],
		["What is the opposite of bad?", "good"],
		["What is 4 times four? (in digits)", "16"],
		["What number comes after 20? (in digits)", "21"],
		["What month comes before July?", "june"],
		["What is fifteen divided by three? (in digits)", "5"],
		["What is 14 minus 4? (in digits)", "10"],
		["What comes next? 'Monday Tuesday Wednesday …'", "thursday"]
  ]

  before_action :set_person, only: [:show, :edit, :update, :destroy, :change_password, :change_state]
  before_action :require_godmother
  skip_before_action :require_godmother, only: [:new, :create, :verify_email]
  before_action :registration_open, only: [:new, :create]

  # GET /people
  def index
    @people = Person.all

    if params[:r]
      @people = @people.where(role: params[:r])
    end

    if params[:s]
      @people = @people.where(state: params[:s])
    end

    if params[:g]
      @people = @people.where(isGodmother: params[:g])
    end
  end

# GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
		@captcha = new_captcha

    if ['mentee', 'mentor'].include?(params[:r])
      @person.role_name = params[:r]
    else
      @person.role_name = :mentee
    end
  end

  # GET /people/1/edit
  def edit
  end

	def change_password
		@person = current_person
	end

  # POST /people
  def create
    @person = Person.new(person_params)
    @captcha = new_captcha

    unless [1, 2].include?(@person.role)
      @person.role = 1
    end

    if params[:address].downcase != QUESTIONS[params[:number].to_i].last
      flash[:alert] = "Are you sure you are human?"
      render :new
    elsif @person.save
      PersonMailer.with(person: @person).verification_email.deliver_now
      redirect_to home_path, notice: "You are successfully registered. We sent you a verification mail to your address <#{@person.email}>. You may have to take a look in your junk folder."
    else
      render :new
    end
  end

  # PATCH/PUT /people/1
  def update
    if person_params[:password]
      if current_person.authenticate(params[:old_password]) && current_person.id == @person.id
        if @person.update(person_params)
          redirect_to @person, notice: 'Password was successfully updated.'
        else
          render :change_password
        end
      else
        flash[:alert] = 'Wrong old password?'
        render :change_password
      end
    elsif @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  def verify_email
    @person = Person.find_by(verification_token: params[:verification_token])

    if @person
      if (Person::STATES.values - [:unverified]).include?(@person.state_name)
        msg = { notice: "Your e-mail address is already verified." }
      elsif @person.state_name == :unverified
        @person.state_name = :verified
        @person.tags.each do |t|
          t.active = true
          t.save
        end

        if @person.save
          PersonMailer.with(person: @person).new_person_email.deliver_now

          msg = { notice: "Your e-mail address was successfuly verified.\nYour request will now be forwarded to us (the Chaospatinnen orga team) and we will send you an answer as soon as possible… which can be a while, sorry for that. ^__^" }
        else
          msg = { alert: "Something went wrong. You may want to contact us." }
        end
      else
        msg = { alert: "What are you trying here?!" }
      end
    else
      msg = { alert: "Seems like your verification link is broken. Try copy and paste it by hand." }
    end

    redirect_to home_path, msg
  end

  def change_state
    if !Person::STATES.keys.include?(params[:state])
      @person.state = params[:state]

      if @person.save
        redirect_to @person, notice: "State was successfully updated to: #{@person.state_name.to_s.humanize}"
      else
        redirect_to @person, alert: 'Something went wrong.'
      end
    else
      redirect_to @person, alert: 'Invalid state.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find_by(random_id: params[:random_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:tag_list, :role_id, :random_id, :verification_token, :name, :pronoun, :email, :about, :password, :password_confirmation, :is_godmother)
  end

  def new_captcha
    flash = {}
    captcha = [rand(QUESTIONS.size)]
    captcha << QUESTIONS[captcha.first].first
    return captcha
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def tags
    Tag.where(active: true).map { |t| html_escape(t.name) }
  end

  def state_batches
    {
      unverified: 'secondary',
      verified: 'primary',
      okay: 'primary',
      waiting: 'warning',
      in_group: 'primary',
      declined: 'danger',
      done: 'sucess'
    }
  end
end

app/views/people/_form.html.erb
<%= bootstrap_form_with(model: person, local: true) do |form| %>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= form.text_field :pronoun, { type: "text", class: "form-control", placeholder: "e.g. She/They/Xe/He/…" } %>
      <small id="pronoun-help" class="form-text text-muted">This information helps us to form balanced groups.</small>
    </div>

    <div class="form-group col-md-8">
      <%= form.text_field :name, { type: "text", class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <%= form.text_field :email, { type: "email", class: "form-control" } %>
    <small id="email-help" class="form-text text-muted">We will send you e-mail. So, this has to be a real address. For real. You know? Real.</small>
  </div>

  <div class="form-group">
    <%= form.text_area :about, { rows: 8, class: "form-control", placeholder: "Something about yourself, why you registered at the chaos mentors and what your interests are." } %>
  </div>

  <div class="form-group">
    <%= form.text_field :tag_list, { placeholder: "e.g.: english, german, coding, antifa, security, freifunk, feminism, …", data: raw(tags) } %>
    <small id="pronoun-help" class="form-text text-muted">Please give yourself a few tags, describing the languages you speak and your interests. This helps us to form fitting groups.</small>
  </div>

  <% if current_person.isGodmother? %>
    <div class="form-group">
      <%= form.select :role_id, [
        ["Mentee", 1],
        ["Mentor", 2],
        ["Godmother Only", 3]
      ] %>
    </div>
  <% end %>

  <% if current_person.isGodmother? && @person != current_person  && @person.role == 2 %>
    <div class="form-group">      
      <%= form.check_box :is_godmother %>
    </div>
  <% end %>

  <% if action_name == 'new' || action_name == 'create' -%>
    <div class="form-group">
      <label>
        Question: <%= @captcha.last %>
      </label><br>
      <label for="address">Answer</label>
      <input class="form-control" type="text" name="address" />
      <small id="pronoun-help" class="form-text text-muted">Sorry, too many spam bots out there.</small>
    </div>
    <input value="<%= @captcha.first %>" type="hidden" name="number" />
  <% end %>

  <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
    Send
  <% end %>
<% end %>

<%= javascript_tag do %>
  $.availableTags = <%= raw tags.to_json %>;
<% end %>
<%= javascript_include_tag 'people' %>

app/views/people/change_password.html.erb
<h1>Change password</h1>

<%= bootstrap_form_with(model: @person, local: true, method: 'put') do |form| %>
  <div class="form-group">
    <label for="old_password">Old password</label>
    <%= password_field_tag :old_password, nil, { class: "form-control" } %>
  </div>

	<div class="form-group">
    <%= form.password_field :password, { class: "form-control" } %>
  </div>

	<div class="form-group">
    <%= form.password_field :password_confirmation, { class: "form-control" } %>
  </div>

  <%= form.submit 'Send', { class: "btn btn-primary" } %>
<% end %>

app/views/people/edit.html.erb
<h1>Editing <%= @person.role_name.to_s.humanize -%></h1>

<%= render 'form', person: @person %>

app/views/people/index.html.erb
<h1>
  <% if params[:r].to_i == 1 %>
    Mentees
  <% elsif params[:r].to_i == 2 %>
    Mentors
  <% elsif params[:g] == "true" %>
    Godmothers
  <% else %>
    People
  <% end %>
  <small>
    (<%= @people.size %>)
  </small>
</h1>

<p>
  <%= link_to 'New Person', new_person_path %>
</p>

<p>
  <% Person::STATES.each do |k, v| %>
    <% if params[:s].to_i == k %>
      <% badge = state_batches[v] %>
    <% else %>
      <% badge = 'secondary' %>
    <% end %>
    <%= link_to v.to_s.humanize, { controller: 'people', action: 'index', r: params[:r], s: k }, class: "badge badge-#{badge}" %>
  <% end %>
  <%= link_to 'X', { controller: 'people', action: 'index', r: params[:r] }, class: "badge badge-secondary" %>
</p>


<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Random ID</th>
      <th scope="col">Pronoun</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.random_id, person %></td>
        <td><%= person.pronoun %></td>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.tag_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>Register as <%= @person.role_name.to_s.humanize -%></h1>

<%= render 'form', person: @person %>

app/views/people/show.html.erb
<div class="card">
  <div class="card-header">
    <%= @person.name %> (<%= @person.role_name.to_s.humanize %>)
    <span class="badge badge-<%= state_batches[@person.state_name] %> float-right"><%= @person.state_name.to_s.humanize %></span>
  </div>
  <div class="card-body">
    <%= link_to 'Edit', edit_person_path(@person), class: 'btn btn-primary active float-right' %>
    <p>
      <strong>Name:</strong>
      <%= @person.name %>
    </p>

    <p>
      <strong>Pronoun:</strong>
      <%= @person.pronoun %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= link_to @person.email, 'mailto:' + @person.email %>
    </p>

    <p>
      <strong>About:</strong><br>
      <%= simple_format(@person.about) %>
    </p>
    <p>
      <strong>Tags:</strong>
      <%= @person.tag_list %>
    </p>
    <% if @person.group %>
    <p>
      <strong>Group:</strong>
      <%= link_to @person.group.mentors.map { |m| m.name }.join(', '), @person.group %>
    </p>
    <% end %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-4">
    <%= link_to 'Replied and okay', { action: "change_state", random_id: @person, state: 3 }, { class: 'btn btn-primary btn-lg btn-block active' } %>
  </div>
  <div class="col-md-4">
    <%= link_to 'Replied and waiting for answer', { action: "change_state", random_id: @person, state: 4 }, { class: 'btn btn-secondary btn-lg btn-block active' } %>
  </div>
  <div class="col-md-4">
    <%= link_to 'Declined', { action: "change_state", random_id: @person, state: 23 }, { class: 'btn btn-danger btn-lg btn-block active' } %>
  </div>
</div>