config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  get 'home', to: 'static#home'
  get 'contact', to: 'static#contact'
  get 'privacy', to: 'static#privacy'

  resources :people, param: :random_id
  get 'verify_email/:verification_token', to: 'people#verify_email'
  get 'change_password', to: 'people#change_password'
  get 'change_state/:random_id/:state', to: 'people#change_state'

  resources :groups
  get 'done/:id', to: 'groups#done'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :mentors, class_name: 'Person'
  has_many :mentees, class_name: 'Person'

  validates :mentors, presence: true

  def mentors
    Person.where(group_id: self.id).where("role = 2 OR role = 3")
  end

  def mentor_ids
    self.mentors.map { |m| m.id }
  end

  def mentees
    Person.where(group_id: self.id).where(role: 1)
  end

  def mentee_ids
    self.mentees.map { |m| m.id }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_godmother
  before_action :set_group, only: [:show, :edit, :update, :destroy, :done]
  before_action :align_person_state, only: [:edit, :new]

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @mentors = Person.where("role = 2 OR role = 3").where(state: 3)
  end

  # GET /groups/1/edit
  def edit
    @mentees = @group.mentees + Person.where(role: 1).where(state: 3)
    @mentors = @group.mentors + Person.where("role = 2 OR role = 3").where(state: 3)
  end

  # POST /groups
  def create
    @group = Group.new
    @group.mentor_ids = params[:group][:mentor_ids]

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      @mentors = Person.where(role: 2).where(state: 3)
      flash[:alert] = "You have to select a mentor."
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    params[:group][:mentee_ids] ||= []
    params[:group][:mentor_ids] ||= []

    people_ids = params[:group][:mentee_ids] + params[:group][:mentor_ids]

    if @group.update(mentee_ids: people_ids)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  def done
    people = @group.mentors + @group.mentees

    people.each do |p|
      p.state_name = :done
      p.save
    end

    @group.mentors.each do |mentor|
      PersonMailer.with(mentor: mentor).your_mentees.deliver_now
    end

    redirect_to @group, notice: 'Group was successfully updated to done and an email was sent to groups mentor(s).'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:mentor_ids, :entee_ids)
    end

    def align_person_state
      Person.where("state = 5 OR state = 3").each { |p| p.save if p.align_group_state }
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h1>Editing Group <small>(<%= @group.mentors.map { |m| m.name }.join(', ') %>)</small></h1>
<%= bootstrap_form_with(model: @group, local: true) do |form| %>

  <div class="align-items-end">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', @group, { class: 'btn btn-secondary'} %>
  </div>

  <p>
    <a "btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Click to edit group mentors</a>
  </p>

  <div class="collapse" id="collapseExample">
    <h2>Select one or more mentors</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">Pronoun</th>
          <th scope="col">Name</th>
          <th scope="col">Tags</th>
        </tr>
      </thead>

      <tbody>
        <% @mentors.each do |mentor| %>
          <tr>
            <td><%= check_box_tag "group[mentor_ids][]", mentor.id, (mentor.group_id && @group.mentors.include?(mentor)) %></td>
            <td><%= mentor.pronoun %></td>
            <td><%= link_to mentor.name, mentor %></td>
            <td><%= mentor.tag_list %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <h2>Select one or more mentees</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Pronoun</th>
        <th scope="col">Name</th>
        <th scope="col">Tags</th>
      </tr>
    </thead>

    <tbody>
      <% @mentees.each do |mentee| %>
        <tr>
          <td><%= check_box_tag "group[mentee_ids][]", mentee.id, (mentee.group_id && @group.mentees.include?(mentee)) %></td>
          <td><%= mentee.pronoun %></td>
          <td><%= link_to mentee.name, mentee %></td>
          <td><%= mentee.tag_list %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<%= link_to 'Show', @group %> |

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<%= link_to 'New Group', new_group_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Mentor names</th>
      <th scope="col">Mentees count</th>
      <th scope="col">Status</th>
      <th scope="col" colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.mentors.map { |m| m.name }.join(', '), group %></td>
        <td><%= group.mentees.size %></td>
        <td><span class="badge badge-<%= state_batches[group.mentors.first.state_name] %>"><%= group.mentors.first.state_name.to_s.humanize %></span></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1>New Group</h1>

<p>Select one or more mentors</p>

<%= bootstrap_form_with(model: @group, local: true) do |form| %>
<%= form.submit %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Pronoun</th>
      <th scope="col">Name</th>
      <th scope="col">Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @mentors.each do |mentor| %>
      <tr>
        <td><%= check_box_tag "group[mentor_ids][]", mentor.id, (mentor.group_id && @group.mentors.include?(mentor)) %></td>
        <td><%= mentor.pronoun %></td>
        <td><%= link_to mentor.name, mentor %></td>
        <td><%= mentor.tag_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>

app/views/groups/show.html.erb
<h1></h1>
<div class="card">
  <div class="card-header">
    Group <small>(<%= @group.mentors.map { |m| m.name }.join(', ') %>)</small>
    <span class="badge badge-<%= state_batches[@group.mentors.first.state_name] %> float-right"><%= @group.mentors.first.state_name.to_s.humanize %></span>
  </div>
  <div class="card-body">
    <%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-primary active float-right' %>

<h2>Mentors</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Random ID</th>
      <th scope="col">Pronoun</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @group.mentors.each do |mentor| %>
      <tr>
        <td><%= link_to mentor.random_id, mentor %></td>
        <td><%= mentor.pronoun %></td>
        <td><%= mentor.name %></td>
        <td><%= mentor.email %></td>
        <td><%= mentor.tag_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Mentees</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Random ID</th>
      <th scope="col">Pronoun</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Tags</th>
    </tr>
  </thead>

  <tbody>
    <% @group.mentees.each do |mentee| %>
      <tr>
        <td><%= link_to mentee.random_id, mentee %></td>
        <td><%= mentee.pronoun %></td>
        <td><%= mentee.name %></td>
        <td><%= mentee.email %></td>
        <td><%= mentee.tag_list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>
<%= link_to 'Done (send mail to mentor/s)', { action: "done", id: @group}, { class: 'btn btn-primary btn-lg btn-block active' } %>