config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  get 'home', to: 'static#home'
  get 'contact', to: 'static#contact'
  get 'privacy', to: 'static#privacy'

  resources :people, param: :random_id
  get 'verify_email/:verification_token', to: 'people#verify_email'
  get 'change_password', to: 'people#change_password'
  get 'change_state/:random_id/:state', to: 'people#change_state'

  resources :groups
  get 'done/:id', to: 'groups#done'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Chaospatinnen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">Chaospatinnen</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/privacy">Privacy statement</a>
          </li>
        </ul>
        <% if godmother? -%>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'All', people_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Godmothers', { controller: 'people', action: 'index', g: true, s: 3 }, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mentors', { controller: 'people', action: 'index', r: 2, s: 3 }, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mentees', { controller: 'people', action: 'index', r: 1, s: 3 }, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Groups', groups_path, class: "nav-link" %>
          </li>
        </ul>
        |
        <ul class="navbar-nav">
          <li class="nav-item">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/change_password">Change password</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/sessions/destroy">Log out</a>
          </li>
        </ul>
      <% end -%>
      </div>

    </nav>

    <main role="main" class="container">

      <div class="content">
        <%= flash_messages(flash).html_safe %>

        <%= yield %>
      </div>
    </main><!-- /.container -->
  </body>
</html>